swagger: '2.0'
info:
  version: 1.0.0
  title: Invitae Genomic Variants on Heroku
  description: |
    **This example has a working backend hosted in Heroku**

    You can try all HTTP operations described in this Swagger spec.

    Find source code of this API [here](https://github.com/Franklin-Wu/invitae-genomic-variants)
host: nameless-wildwood-39643.herokuapp.com
basePath: /api
schemes:
  - http
  - https
produces:
  - application/json
paths:
  /:
    get:
      responses:
        default:
          description: A JSON object containing an error code.
          schema:
            $ref: '#/definitions/errorResponse'
  '/getGeneNamesStartingWith':
    get:
      parameters:
        - name: prefix
          in: query
          description: The gene name prefix against which to search.
          type: string
          required: true
      responses:
        default:
          description: A JSON object containing an array of gene names.
          schema:
            $ref: '#/definitions/geneNames'
  '/getGenesNamed':
    get:
      parameters:
        - name: name
          in: query
          description: The gene name against which to search.
          type: string
          required: true
      responses:
        default:
          description: A JSON object containing an array of gene objects.
          schema:
            $ref: '#/definitions/genes'
definitions:
  errorResponse:
    type: object
    properties:
      error:
        type: object
        properties:
          code:
            type: integer
          message:
            type: string
  geneNames:
    type: object
    properties:
      data:
        type: array
        items:
          type: object
          properties:
            name:
              description: Gene Name.
              type: string
  genes:
    type: object
    properties:
      data:
        type: array
        items:
          type: object
          properties:
            name:
              description: Gene name.
              type: string
            nchange:
              description: Nucleotide Change.
              type: string
            pchange:
              description: Protein Change.
              type: string
            alias:
              description: Alias.
              type: string
            region:
              description: Region.
              type: string
            rclass:
              description: Reported Classification.
              type: string
            leval:
              description: Last Evaluated.
              type: string
            lupdate:
              description: Last Updated.
              type: string
            url:
              description: URL.
              type: string
