# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

# Column   Header In Original File
# -------  -----------------------
# id       <none>
# name     Gene
# nchange  Nucleotide Change
# pchange  Protein Change
# maps     Other Mappings
# alias    Alias
# trans    Transcripts
# region   Region
# rclass   Reported Classification
# iclass   Inferred Classification
# source   Source
# leval    Last Evaluated
# lupdate  Last Updated
# url      URL
# comment  Submitter Comment

    operations = [
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('id',      models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',    models.CharField(max_length=128,  verbose_name=b'Gene')),
                ('nchange', models.CharField(max_length=2048, verbose_name=b'Nucleotide Change')),
                ('pchange', models.CharField(max_length=2048, verbose_name=b'Protein Change')),
                ('maps',    models.CharField(max_length=2048, verbose_name=b'Other Mappings')),
                ('alias',   models.CharField(max_length=2048, verbose_name=b'Alias')),
                ('trans',   models.CharField(max_length=2048, verbose_name=b'Transcripts')),
                ('region',  models.CharField(max_length=2048, verbose_name=b'Region')),
                ('rclass',  models.CharField(max_length=2048, verbose_name=b'Reported Classification')),
                ('iclass',  models.CharField(max_length=2048, verbose_name=b'Inferred Classification')),
                ('source',  models.CharField(max_length=2048, verbose_name=b'Source')),
                ('leval',   models.CharField(max_length=2048, verbose_name=b'Last Evaluated')),
                ('lupdate', models.CharField(max_length=2048, verbose_name=b'Last Updated')),
                ('url',     models.CharField(max_length=2048, verbose_name=b'URL')),
                ('comment', models.CharField(max_length=8192, verbose_name=b'Submitter Comment')),
            ],
        ),
    ]
